version: '3'
services:
  myapp-main:
    image: golf_tournament_api:latest
#    image: walidjer/golf_tournament_api:latest
    ports:
      - 8080:8080
    environment:
      #- spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_tournament
      - spring.datasource.url=jdbc:mysql://golf-tournament-db-instance-1.cg99fuzej1dr.us-east-1.rds.amazonaws.com/golf_tournament
      - spring.datasource.password=WalidJerjawi84
      - spring.datasource.username=admin
#      - spring.datasource.username=root